
// Allow GitHub image rendering
:imagesdir: ../../images

[[ga-enlinkd]]
== Enhanced Linkd

_Enhanced Linkd_ (Enlinkd) has been designed to get a snapshot of the neighbors from the device perspective.
Every relationship discovered by _Enlinkd_ are called _Links_.
The term _Link_ with _Enlinkd_ is not used in the same manner as in _Layer 2_ network speech for _Layer 2_, i.e. _Link Layer Discovery Protocol_.
A _Link_ with _Enlinkd_ is a high level concept and describes a connection between two _OpenNMS Nodes_.
These _Links_ can be discovered based on _Layer 2_ or _Layer 3_ protocols.
The data to discover _Links_ is based on information provided from _SNMP agents_.
For this reason, _SNMP_ must be configured properly and has to be enabled for the _OpenNMS_ server.

The coming section describe the _Enlinkd_ daemon and his configuration.
Additionally the supported _Link discovery_ implementations will be described and which SNMP OIDs are supported to gather the _Links_ between _Nodes_.

=== Enlinkd Daemon

Essentially it asks each device the following question: "What is the network topology from your point of view".
From this point of view this will only provide local topology discovery features.
It does not attempt to discover global topology or doing any correlation with the data coming from other nodes.

For large environments the behavior of _Enlinkd_ can be configured.
During the _Link_ discovery process informational and error output is logged to a global log file.

.Global configuration and log file for _Enlinkd_
[options="header, autowidth"]
|===
| File                        | Location            | Description
| `enlinkd-configuration.xml` | `$OPENNMS_HOME/etc` | Global configuration for the daemon process
| `enlinkd.log`               | `$OPENNMS_HOME/log` | Global _Enlinkd_ log file
|===

.Configuration file for _Enlinkd_
[source, xml]
----
<?xml version="1.0" encoding="ISO-8859-1"?>
<enlinkd-configuration threads="5"
                     initial_sleep_time="60000"
                     rescan_interval="86400000"
                     use-cdp-discovery="true"
                     use-bridge-discovery="true"
                     use-lldp-discovery="true"
                     use-ospf-discovery="true"
                     use-isis-discovery="true"
                     />
----

.Descriptione for global configuration parameter
[options="header, autowidth"]
|===
| Attribute              | Type      | Default    | Description
| `threads`              | _Integer_ | `5`        | Number of parallel threads used to discover the topology.
| `initial_sleep_time`   | _Integer_ | `60000`    | Time in milliseconds to wait for discovering the topology after OpenNMS is started.
| `rescan_interval`      | _Integer_ | `86400000` | Interval to rediscover and update the topology in milliseconds.
| `use-cdp-discovery`    | _Boolean_ | `true`     | Enable or disable topology discovery based on _CDP_ information.
| `use-bridge-discovery` | _Boolean_ | `true`     | Enable or disable algorithm to discover the topology based on the _Bridge MIB_ information.
| `use-lldp-discovery`   | _Boolean_ | `true`     | Enable or disable topology discovery based on _LLDP_ information.
| `use-ospf-discovery`   | _Boolean_ | `true`     | Enable or disable topology discovery based on _OSPF_ information.
| `use-isis-discovery`   | _Boolean_ | `true`     | Enable or disable topology discovery based on _IS-IS_ information.
|===
