// Allow GitHub image rendering
:imagesdir: ../../images

=== IS-IS Discovery

IS-IS links are found walking the isisISAdjTable that is defined in ISIS-MIB, (mib-rfc4444.txt) in standard mibs under Juniper junos supported Mib tree.
In this table you got the information you need to find the Adjency Intermediate System.
The information about Is-Is is stored into two tables: isisElement and isisLink.
isisElement contains the ISISSysID a unique identifier of the "Intermediate System" (that is the name for the Router in iso protocols).
Each entry in this table (snmp) represents a link, let me say, a one direction link from the Intermediate system that is queried to the Adj Intermediate systems running IS-IS and "let me say" peering with the source router.
If two routers let me say IS-A and IS-B support ISIS-MIB you will find two entries in opennms, one that is the direction from IS-A to IS-B get walking IS-A adjTable and the way back from IS-B to IS-A.
get walking IS-B adjTable
Here you find the definition of the tables in our database:

[options="header, autowidth"]
|===
| Name | OID | Description
| _isisSysID_         | `1.3.6.1.2.1.138.1.1.1.3.0`  | The ID for this Intermediate System.
                                                       This value is appended to each of the area addresses to form the Network Entity Titles.
                                                       The derivation of a value for this object is implementation specific.
                                                       Some implementations may automatically assign values and not permit an SNMP write, while others may require the value to be set manually.
                                                       Configured values *must* survive an agent reboot.
| _isisSysAdminState_ | `.1.3.6.1.2.1.138.1.1.1.8.0` | The administrative state of this Intermediate System.
                                                       Setting this object to the value `on` when its current value is `off` enables the Intermediate System.
                                                       Configured values *must* survive an agent reboot.
| _isisSysObject_     | `.1.3.6.1.2.1.138.1.1.1`     | isisSysObject
|===
