
// Allow GitHub image rendering
:imagesdir: ../../images

==== CDP Discovery

The _CDP_ discovery is made walking the link:http://tools.cisco.com/Support/SNMP/do/BrowseMIB.do?local=en&step=2&mibName=CISCO-CDP-MIB[CISCO-CDP-MIB] and link:http://tools.cisco.com/Support/SNMP/do/BrowseMIB.do?local=en&step=2&mibName=CISCO-VTP-MIB[CISCO-VTP-MIB].
The following OIDs are supported to discover and build the _CDP_ network topology.

.Supported OIDS from the CISCO-CDP-MIB to discover links
[options="header, autowidth"]
|===
| Name                      | OID                             | Description
|                           | `.1.3.6.1.2.1.2.2.1.2`          |
|                           | `.1.3.6.1.4.1.9.9.23.1.1.1.1.6` |
| _cdpCacheTableEntry_      | `.1.3.6.1.4.1.9.9.23.1.2.1.1`   |
| _cdpCacheAddressType_     | `.1.3.6.1.4.1.9.9.23.1.2.1.1.3` | An indication of the type of address contained in the corresponding instance of _cdpCacheAddress_.
| _cdpCacheAddress_         | `.1.3.6.1.4.1.9.9.23.1.2.1.1.4` | The (first) network-layer address of the device's SNMP-agent as reported in the Address _TLV_ of the most recently received _CDP_ message.
                                                                For example, if the corresponding instance of _cacheAddressType_ had the value `ip(1)`, then this object would be an IP-address.
| _cdpCacheVersion_         | `.1.3.6.1.4.1.9.9.23.1.2.1.1.5` | The Version string as reported in the most recent _CDP_ message.
                                                                The zero-length string indicates no Version field _(TLV)_ was reported in the most recent _CDP_ message.
| _cdpCacheDeviceId_        | `.1.3.6.1.4.1.9.9.23.1.2.1.1.6` | The _Device-ID_ string as reported in the most recent _CDP_ message.
                                                                The zero-length string indicates no _Device-ID_ field _(TLV)_ was reported in the most recent _CDP_ message.
| _cdpCacheDevicePort_      | `.1.3.6.1.4.1.9.9.23.1.2.1.1.7` | The _Port-ID_ string as reported in the most recent _CDP_ message.
                                                                This will typically be the value of the _ifName_ object (e.g., `Ethernet0`).
                                                                The zero-length string indicates no _Port-ID_ field _(TLV)_ was reported in the most recent _CDP_ message.
| _cdpCachePlatform_        | `.1.3.6.1.4.1.9.9.23.1.2.1.1.8` | The Device's Hardware Platform as reported in the most recent _CDP_ message.
                                                                The zero-length string indicates that no Platform field _(TLV)_ was reported in the most recent _CDP_ message.
| _cdpGlobalRun_            | `.1.3.6.1.4.1.9.9.23.1.3.1.0`   | An indication of whether the Cisco Discovery Protocol is currently running.
                                                                Entries in _cdpCacheTable_ are deleted when CDP is disabled.
| _cdpGlobalDeviceId_       | `.1.3.6.1.4.1.9.9.23.1.3.4.0`   | The device ID advertised by this device.
                                                                The format of this device id is characterized by the value of _cdpGlobalDeviceIdFormat_ object.
| _cdpGlobalDeviceIdFormat_ | `.1.3.6.1.4.1.9.9.23.1.3.7.0`   | An indication of the format of Device-Id contained in the corresponding instance of _cdpGlobalDeviceId_.
                                                                User can only specify the formats that the device is capable of as denoted in _cdpGlobalDeviceIdFormatCpb_ object. +
                                                                *_serialNumber(1):_* indicates that the value of _cdpGlobalDeviceId_ object is in the form of an _ASCII_ string contain the device serial number. +
                                                                *_macAddress(2):_* indicates that the value of _cdpGlobalDeviceId_ object is in the form of Layer 2 MAC address. +
                                                                *_other(3):_* indicates that the value of _cdpGlobalDeviceId_ object is in the form of a platform specific _ASCII_ string contain info that identifies the device.
                                                                For example: _ASCII string_ contains _serialNumber_ appended/prepened with system name.
|===

.Supported OIDS from the CISCO-VTP-MIB.
[options="header, autowidth"]
|===
| _vtpVersion_              | `.1.3.6.1.4.1.9.9.46.1.1.1.0`   | The version of VTP in use on the local system.
                                                                A device will report its version capability and not any particular version in use on the device.
                                                                If the device does not support _VTP_, the version is _none(3)_.
| _ciscoVtpVlanState_       | `.1.3.6.1.4.1.9.9.46.1.3.1.1.2` |
| _ciscoVtpVlanType_        | `.1.3.6.1.4.1.9.9.46.1.3.1.1.3` |
| _ciscoVtpVlanName_        | `.1.3.6.1.4.1.9.9.46.1.3.1.1.4` |
|===
